# Generated by Django 4.2 on 2023-09-28 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('birth_place', models.CharField(max_length=50)),
                ('custom_slug_profile', models.SlugField(blank=True, max_length=15, null=True, unique=True)),
                ('private_profile', models.BooleanField(default=False)),
                ('show_birthday', models.BooleanField(default=True)),
                ('friends', models.ManyToManyField(blank=True, to='helenite_app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField(blank=True, max_length=300)),
                ('post_image', models.ImageField(blank=True, upload_to='post_images')),
                ('post_publication_date', models.DateTimeField(auto_now_add=True)),
                ('post_slug', models.SlugField(blank=True, max_length=15, null=True, unique=True)),
                ('post_likes', models.ManyToManyField(related_name='liked_posts', through='helenite_app.Like', to=settings.AUTH_USER_MODEL)),
                ('post_parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='like_parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helenite_app.post'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=500)),
                ('comment_publication_date', models.DateTimeField(auto_now_add=True)),
                ('comment_parent_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helenite_app.post')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('like_owner', 'like_parent_post')},
        ),
    ]
