version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: ./data/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  react:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - db

volumes:
  postgres-data:
